version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.50.1
    container_name: monitoring_prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/secrets:/etc/prometheus/secrets:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=5d'
    networks:
      - monitoring_network

  node-exporter:
    image: prom/node-exporter:v1.7.0
    container_name: monitoring_node_exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - metrics_data:/var/lib/node_exporter
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
    networks:
      - monitoring_network

  cadvisor:
    image: zcube/cadvisor:latest
    container_name: monitoring_cadvisor
    restart: unless-stopped
    privileged: true
    command:
      - '-housekeeping_interval=1s'
      - '-disable_metrics=disk,percpu,sched,process'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - monitoring_network

volumes:
  prometheus_data:

  metrics_data:


networks:
  monitoring_network:
    driver: bridge
