global:
  # THE OVERCLOCK: Scrape every second for High-Res Live Data
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['monitoring_node_exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['monitoring_cadvisor:8080']

remote_write:
  - url: "${GRAFANA_REMOTE_WRITE_URL}"
    basic_auth:
      username: "${GRAFANA_REMOTE_WRITE_USER}"
      password_file: /etc/prometheus/secrets/api_key